worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Evita que Nginx muestre su versión en los headers (seguridad)
    server_tokens off;

    # Backend de la API Principal
    upstream api_backend {
        # Docker DNS balanceará automáticamente entre las réplicas del servicio "api"
        server api:3000;
    }

    # Backend del Microservicio de Búsqueda
    upstream search_backend {
        server search-service:3001;
    }

    server {
        listen 80;

        # Balanceador para la API Principal
        # no usamos /api/ por que las rutas internas de index.ts no lo tienen
        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://api_backend;
            
            # Pasar headers importantes
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Balanceador para el Microservicio de Búsqueda
        # No corto la ruta porque SearchRoutes.ts sí tiene el prefijo /search/
        location /search/ {
            proxy_pass http://search_backend;
            
            # Pasar headers importantes
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Ruta por defecto para verificar el balanceador
        location / {
            return 200 'Balanceador Nginx funcionando correctamente.\n';
            add_header Content-Type text/plain;
        }
    }
}