version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: restaurante_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: restaurante_auth
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurante_api
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    depends_on:
      - db
      - keycloak
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: