name: CI Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: Tarea_1/backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: Tarea_1/backend

      - name: Run tests
        run: npm test -- --detectOpenHandles
        working-directory: Tarea_1/backend

      - name: Build Docker image
        run: docker build -t restaurante-backend .
        working-directory: Tarea_1

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: |
          docker tag restaurante-backend ${{ secrets.DOCKER_USERNAME }}/restaurante-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurante-backend:latest